### ISSUE TITLE
Example and template

### ISSUE THREAD

**Issue by kofifus** [icenorge/DotNetCore.WindowsServices#8]
It would be really helpful if there can be a guide or sample project for using this to create a .NET Core 3 console App as a windows service.

It would be even more helpful if there would be a VS17-19 project template for that !

Thanks

**Comment by johnkors** [comment]
Hi, did you read the readme.md?

It explains how to use it in the [usage section](https://github.com/icenorge/DotNetCore.WindowsServices/blob/master/README.md#usage)

**Comment by johnkors** [comment]
Here's a sample console app as well: https://github.com/icenorge/DotNetCore.WindowsServices/blob/master/source/console.app/

**Comment by kofifus** [comment]
got it thx!
